sudo: required
services:
  - docker

before_install:
  - docker build -t thevishalnair/docker-react -f Dockerfile.dev .

script:
  - docker run thevishalnair/docker-react npm run test -- --coverage